### ISSUE TITLE
What is the rational behind y_emin and y_emax calculation in PreAcon class?

### ISSUE THREAD

**Issue by devvaibhav455** [criogenox/B-Equivalent-Conicity-Calculation#4]
I am trying to do something similar to you by following EN15302, but to me, the instructions are not super clear. Simultaneously, I am also trying to get more hints from your code which I believe is certainly helpful given the scarce resources related to "Equivalent Conicity" that are available openly on the internet. So, thanks a lot from the heart to you. However, I have a couple of questions related to the procedure that you followed that I have explained below.

I got the S curve by integrating the delta_r function. Now, the standard asks to find out the y_emin and y_emax corresponding to a y value but does not exactly mention how. In your approach, first, you calculate `idmins` which is the index where delta_r ~= 0. In the symmetric case (cas == 2), it should be exactly halfway in the S curve but for asymmetric case (cas == 1), find the index for the  minimum value > 0.

After that, you cut the S curve into two parts and store the later part (from `idmins` till the `end`) into `sip`. 

I have a couple of questions here which I believe are easier to understand if I know the rational behind this.

1. Why is `yemm` has length `idmins-1` and not something else. Forget about the other dimension 6 ( I figured out that part).
2. Why do you do `sip[i] - si`? I think that's the main logic.
3. Why do `y_emin` and `y_emax` have the values `j` and `idxd+idmins-1;`
4.  `yemm[j][5] = s[j];` This is the C value in the standard but why?

Can you please help? Thank you in advance.

**Comment by devvaibhav455** [comment]
@criogenox  Nice to meet you as well. Been trying to use robotics in railway :) Did you get a chance to look at the code?

**Comment by criogenox** [comment]
Hi again. I'm actually working on porting the entire code to another, concise language. Stay tune.
